version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t python/lib/python3.11/site-packages/ 
  build:
    commands:
      - echo Build started on `date`
      - cd python/lib/python3.11/site-packages/
      - zip -r ../../../../dependencies.zip .
      - cd ../../../../
      - zip -g dependencies.zip lambda_function.py
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading the package to S3...
      - aws s3 cp dependencies.zip s3://dibyaranjan-glue/ci-cd/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name lambda-cicd --s3-bucket lambda-builds-zip --s3-key deployment_package.zip
      - echo "Deployment complete!"